# Generated by Django 3.2.7 on 2021-10-14 08:31

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Чингиз Айтматов', max_length=100, no_check_for_status=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='роман', max_length=100, no_check_for_status=True),
        ),
    ]
