# Generated by Django 3.2.7 on 2021-10-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_tweet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweet',
            new_name='Product',
        ),
    ]
