# Generated by Django 3.2.7 on 2021-10-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_tweet_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
